[build]
  command = "npm ci && npm install -g typescript @types/react @types/node @netlify/functions && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':!dashboard' ':!onboarding'"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_PUBLIC_SUPABASE_URL = "https://mhknphytydmucodqtprd.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oa25waHl0eWRtdWNvZHF0cHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNzY4MzUsImV4cCI6MjA1MTg1MjgzNX0.gXDycogT9_teh7BRL1LX_7i_M8GPbtPjpT6qxSaj-Q8"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oa25waHl0eWRtdWNvZHF0cHJkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNjI3NjgzNSwiZXhwIjoyMDUxODUyODM1fQ.NFJSf86u3u6ph5EsStwkmU939FIzIhoBG_g2q6QdkFU"
  NEXT_PUBLIC_SITE_URL = "${URL}"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200
  force = true

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: http:; style-src 'self' 'unsafe-inline' https: http: fonts.googleapis.com cdnjs.cloudflare.com; font-src 'self' data: fonts.gstatic.com cdnjs.cloudflare.com; img-src 'self' data: https: http: blob:; connect-src 'self' https: http: wss: *.supabase.co *.supabase.in; frame-src 'self' https: http:;"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true 

[[redirects]]
  from = "/onboarding"
  to = "/"
  status = 200
  conditions = {Role = ["authenticated"]}
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200
  conditions = {Role = ["authenticated"]}
  force = true 

[[redirects]]
  from = "/settings"
  to = "/settings/index.html"
  status = 200
  conditions = {Role = ["authenticated"]}
  force = true 